openapi: 3.0.3
info:
  title: API de Citas
  description: API para la gestión de citas médicas
  version: 1.0.0
paths:
  /api/appointments:
    post:
      summary: Crear una cita médica
      tags:
        - Appointments
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                doctor:
                  type: string
                  example: "64aee3f12b4c1f74e1234567"
                date:
                  type: string
                  format: date-time
                  example: "2025-07-15T10:30:00Z"
                notes:
                  type: string
                  example: "Consulta general"
      responses:
        '201':
          description: Cita creada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cita creada correctamente"
                  appointment:
                    $ref: '#/components/schemas/Appointment'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Obtener todas las citas (admin)
      tags:
        - Appointments
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de todas las citas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/appointments/user:
    get:
      summary: Obtener citas del usuario autenticado
      tags:
        - Appointments
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de citas del usuario
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/appointments/{id}:
    put:
      summary: Actualizar una cita
      tags:
        - Appointments
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: "64b0c34cfcc32145e1234567"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date-time
                  example: "2025-07-20T14:00:00Z"
                reason:
                  type: string
                  example: "Control de resultados"
      responses:
        '200':
          description: Cita actualizada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cita actualizada correctamente"
                  appointment:
                    $ref: '#/components/schemas/Appointment'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Cita no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Eliminar una cita
      tags:
        - Appointments
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: "64b0c34cfcc32145e1234567"
      responses:
        '200':
          description: Cita eliminada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cita eliminada correctamente"
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Cita no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/appointments/doctors:
    get:
      summary: Obtener lista de doctores (admins)
      tags:
        - Appointments
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de doctores
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "64aee3f12b4c1f74e1234567"
                    first_name:
                      type: string
                      example: "Martín"
                    last_name:
                      type: string
                      example: "Gómez"
                    email:
                      type: string
                      example: "martin.gomez@hospital.com"
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Appointment:
      type: object
      properties:
        _id:
          type: string
          example: "6501c2f7a8b9d1b987654321"
        user:
          type: string
          description: ID del paciente (ref a User)
          example: "64f1c2b7e8f1c9a123456789"
        patient_name:
          type: string
          nullable: true
          example: "Pedro Gómez"
        doctor:
          type: string
          description: ID del doctor (ref a User con role admin)
          example: "64f1c2b7e8f1c9a987654321"
        date:
          type: string
          format: date-time
          example: "2025-09-01T14:30:00Z"
        status:
          type: string
          enum: [pending, confirmed, cancelled]
          example: "pending"
        notes:
          type: string
          example: "Paciente con antecedentes de alergia"
        lastNotified:
          type: string
          format: date-time
          example: "2025-09-01T12:00:00Z"
    Error:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: "Mensaje de error"
      required:
        - status
        - message